NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.company2.karbonbloc.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.company2.karbonbloc.com-cert.pem
    OrganizationalUnitIdentifier: peer
